global:
  scrape_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'kea-dhcp-shailamartinez'
    static_configs:
      - targets: ['172.24.63.10:9547']

  - job_name: 'rogue-detector-shailamartinez'
    static_configs:
      - targets: ['172.24.63.10:9101']